version: "3"
services:
  feezy-auth:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      PORT: 80
      # NODE_ENV: production # to test production builds enable this.
      MONGO_DB_URL: mongodb://feezy-auth-mongodb:27017/feezy-auth
    ports:
      - 8099:80
    volumes:
      - feezy-auth-node-modules-volume:/app/node_modules
      - ./src:/app/src
    deploy:
      replicas: 1
    depends_on:
      - feezy-auth-mongodb

  feezy-auth-mongodb:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - feezy-auth-mongodb-volume:/data/feezy-auth-mongodb/db
    ports:
      - 20017:27017
    command:
      - mongod

volumes:
  feezy-auth-node-modules-volume:
  feezy-auth-mongodb-volume:
